### ISSUE TITLE
Schéma Epistemon.rng

### ISSUE THREAD

**Issue by AnneLHuet** [OBVIL/faceties#10]
- Utilisation du schéma epistemon développé par l'université de Tours
- Déclaration du schéma en en-tête de fichier:
```
<?xml-model href="http://www.bvh.univ-tours.fr/XML-TEI/schema/BVH_Epistemon.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-modelhref="http://www.bvh.univ-tours.fr/XML-TEI/schema/BVH_Epistemon.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```
- Attention : le schéma invalide le `<header>` de la version "Teinte" : balises `<availability>` `<creation>` et `<index>`. Adapter le `<header>`

**Comment by AnneLHuet** [comment]
@BineauJeanne @NolwennCH 

J'ai modifié le schéma .rng des BVH pour qu'il s'adapte aux métadonnées de l'Obvil pour le header. Les balises `<index>` ne sont pas prises en charge par le schéma, et je pense que ce n'est pas pertinent de le modifier pour la partie `<body>` (le but d'utiliser le schéma étant de s'adapter à ce qui a précédemment était fait pour les BVH). On voit ça demain car cela implique probablement des modifications dans vos transfo #24 #23 ... :'(

**Comment by BineauJeanne** [comment]
La partie initialement mise dans `<index>` peut être intégrer dans le teiheader, dans une balise textClass : 
```xml
         <textClass>
            <keywords>
               <term n="lieu">[premier lieu où se passe la narration]</term>
               <term n="lieu">[deuxième lieu etc.]</term>
               <term n="personnage">[premier personnage, soit nom + fonction, soit nom, soit
                  fonction (drapière, bourgeois, curé)]</term>
               <term n="personnage">[deuxième personnage,etc.]</term>
            </keywords>
         </textClass>
```
