### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by AnneLHuet** [OBVIL/faceties#11]
**Créer une documentation claire pour le dépôt en enrichissant le README.md**
pour la création d'un fichier markdown, voir la documentation à l'adresse suivante : https://www.markdownguide.org/basic-syntax/

Pour la visualisation d'un fichier markdown dans firefox, télécharger le plug-in à l'adresse suivante : https://addons.mozilla.org/fr/firefox/addon/markdown-viewer-chrome/

- Préciser dans quel cadre le projet est développé (voir la page de l'Obvil)

- Mentionner les outils utilisés (le schéma, les xsl)

- Ajouter des précisions concernant l'encodage des fichiers

Un conseil : c'est beaucoup plus simple d'enrichir régulièrement ce fichier au cours de ton travail !

**Comment by BineauJeanne** [comment]
Le "_readme_" est en cours (je finis d'y inscrire les différentes manip et je le _commit_).

**Comment by NolwennCG** [comment]
Encodage de l'odt : 
- pour les `<term>`, la valeur de l'`<idno>` ne doit pas être un hyperlien car celui-ci ne passe pas dans la T1
- encoder les `<ab>` comme tel (déjà ajouté dans la transformation)
