### ISSUE TITLE
problèmes des césures

### ISSUE THREAD

**Issue by BineauJeanne** [OBVIL/faceties#15]
# Problème  des césures

Comment marquer les césures dans la transformation `xsl`? 

 **1. Césures simple**

rendu attendu : `mot-<lb rend="hyphen">`

**2. Césure dans les abréviations** 

-> faire en sorte que la césure apparaisse dans le `<orig>` et le `<reg>`

``` xml
<choice>
<orig>
fa-
<lb rend="hyphen"/>
ueur
</orig>
<reg>
fa-
<lb rend="hyphen"/>
veur
</reg>
</choice>
```

**3. Césures manquantes/implicites (celles qui n'ont pas été inscrites par l'imprimeur)**

-> sont à traiter comme des erreurs d'imprimerie avec les balises `<sic>` et `<corr>` dans un `<choice>`

résultat attendu :
``` xml
<choice>
<sic>
fa
ueur
</sic>
<corr>
fa-
<lb rend="hyphen"/>
veur
</corr>
</choice>
```

rendu pour le moment ; 
``` xml
<choice>
                     <sic>le</sic>
                     <corr>le-<lb rend="hyphen"/>
                     </corr>
                  </choice>
                  <lb/>quel
```

-> problèmes : 
- la fin du mot se retrouve au `<lb>` suivant
- problème pour les mots qui comportent déjà une version `<orig>/<reg>` : il s'agirait de les placer dans le `<sic>`
```xml

<choice>
<sic>
<orig>mot</orig>
<reg>mot avec abréviation résolue</reg>
</sic>
<corr>mot avec marque de césure et la résolution d'abréviation</corr>
<choice>
```

**Comment by BineauJeanne** [comment]
Problème résolu pour les césures normales et pour celles qui sont implicites. Reste celles qui sont enchâssées dans des balises `orig`/`reg` et `sic`/`corr`

**Comment by AnneLHuet** [comment]
Je ferme cette issue puisque tu as résolu la question des césures pour l'XSL. Merci !
