### ISSUE TITLE
Création d'une XSL propre au projet (word > xml)

### ISSUE THREAD

**Issue by AnneLHuet** [OBVIL/faceties#20]
**Création d'une XSL spécifique au projet pour la transformation des fichiers word en fichier xml, afin de faciliter le travail d'encodage.**

**Comment by BineauJeanne** [comment]
Test sur le fichier 005 qui fonctionne pour la transfo. 
Reste à faire : 
* [x] un fichier .odt contenant l'ensemble des styles utilisés dans les feuilles de transformations et explication de leurs utilisations
* [x] ajouter un style distinct pour les langues

**Comment by NolwennCG** [comment]
XSLT réussi.
