### ISSUE TITLE
Création d'une XSL [XML -> XML (abréviations)]

### ISSUE THREAD

**Issue by AnneLHuet** [OBVIL/faceties#23]
Création d'une XSL pour la résolution des abréviations, à partir du modèle des BVH. L'encodage doit être être fait au caractère et non au mot. :)

**Comment by BineauJeanne** [comment]
Il reste encore des problèmes de hiérarchisation du texte à régler sur cette transformation

**Comment by NolwennCG** [comment]
XSLT réussi et complet.
