### ISSUE TITLE
Nouveaux styles

### ISSUE THREAD

**Issue by NolwennCG** [OBVIL/faceties#37]
1. Déterminer le balisage (selon le schéma BVH)
2. Ajouter les nouveaux styles aux transformations
- [x] lettrine2
- [x] lettrine3
- [x] lettrine4
- [x] lettrine5
- [x] lettrine6
- [x] lettrine7
- [x] lettrine8
- [x] lettrine9
- [x] restitution (pour les lettres un peu effacées)
- [x] style distinct pour les langues

**Comment by NolwennCG** [comment]
## Les lettrines : 
Voici ce qui a été choisi pour l'instant : `<c type="lettrine" style="font-size:2em">L</c>ettrine`, cela permet de donner toutes les informations sans ajouter trop d'attributs. Il faudra compléter cela par la css : 
```css
c.lettrine {
	float:left;
	text-indent:0;
	margin-right:0.1em;
}
```
Modification du schéma .rng (ajout de l'élément `c`) : 
```xml
<define name="c">
      <element name="c">
         <a:documentation xmlns:a="http://relaxng.org/ns/compatibility/annotations/1.0">(character) represents a character. [17.1. Linguistic Segment Categories]</a:documentation>
         <text/>
         <ref name="macro.xtext"/>
         <ref name="att.global.attribute.xmlid"/>
         <ref name="att.global.attribute.n"/>
         <ref name="att.global.attribute.xmllang"/>
         <ref name="att.global.attribute.xmlbase"/>
         <ref name="att.global.attribute.xmlspace"/>
         <ref name="att.global.rendition.attribute.rend"/>
         <ref name="att.global.rendition.attribute.style"/>
         <ref name="att.global.rendition.attribute.rendition"/>
         <ref name="att.typed.attribute.type"/>
         <ref name="att.typed.attribute.subtype"/>
         <empty/>
      </element>
   </define>
```

**Comment by NolwennCG** [comment]
## Restitution : 
- Sans avoir besoin de changer le schéma des BVH : `<damage>`
- <damage> (dommage) sert à encoder une zone qui a subi des dommages dans le manuscrit témoin du texte. 
```xml
<damage type="efface">R</damage>estitution
```
## Langue particulière : 
- Sans avoir besoin de changer le schéma des BVH : `<foreign>`
- (étranger) reconnaît un mot ou une expression comme appartenant à une langue différente de celle du contexte.
- utilisation de la norme ISO 639-2B : https://www.loc.gov/standards/iso639-2/php/code_list.php
   - italien : ita
   - latin : lat
   - moyen-français : frm
```xml
<damage xml:lang="ita">Citation en italien</damage>
```
- @BineauJeanne le mieux serait de nommer le style de l'odt ainsi : `foreign_[code]` (exemple : `foreign_ita`). J'ai aussi besoin de savoir si les bouts en langues étrangères sont des mots/phrases isolées ou intégrées au texte.

**Comment by BineauJeanne** [comment]
Pour les langues étrangères, pour le moment j'ai eu que du latin, pour des locutions, proverbes (phrases en général assez courtes) intégrés au texte. 
J'avais mis "lang_lat", je change en foreign_lat ou autres (selon ce que je rencontre).
