### ISSUE TITLE
Pied-de-mouche

### ISSUE THREAD

**Issue by NolwennCG** [OBVIL/faceties#40]
Faut-il changer notre balisage pour les pieds de mouches ? 
- Nous : `<orig>⸿</orig>`
- Epistémon : `<g type="pied_de_mouche">⸿</g>`

**Comment by AnneLHuet** [comment]
@NolwennCH, je vous renvoi à la page suivante http://www.bvh.univ-tours.fr/XML-TEI/odd/odd.html#g

Si l'on utilise cet élément pour les pieds de mouche, il faut l'utiliser également pour les autres caractères non standard s'il y en a
