### ISSUE TITLE
Renommer les styles ODT

### ISSUE THREAD

**Issue by NolwennCG** [OBVIL/faceties#42]
Afin que les XSLT soient pérennes et que les ODT soient plus facile à styler pour les futurs stagiaires et chercheurs, il serait bien de changer le nom de styles ODT pour qu'ils soient plus logiques (suivi par des changements dans l'XSLT).
- L'idéal est de **regrouper les styles similaires sous un nom de style similaire** : `titre`, `style`, `lettrine`, etc (exemple : `lettrine2`, `lettrine3`). 
- Cela permet de rajouter des styles à ces groupes sans avoir à toucher à l'XSTL (exemple : `lettrine12`) car ces styles seront traités dans des boucles (donc de manière automatique). 
- Les groupes sont déterminés par le nom de leur balise en XML (pour l'exemple ci-dessous, le style odt sera `hi_[A, B ou C]`) : 
```xml
<hi rend="A"></hi>
<hi rend="B"></hi>
<hi rend="C"></hi>
```
### Titres :
- (contenu) `_3c_Pagedetitre_5f_sous-titre_3e_ ` : en `titre_h1`
- `h` : en `titre_h2`
## Titres (front) : 
- (front) `_3c_Pagedetitre_5f_titre_3e_` : `front_main`
- (front) `_3c_Pagedetitre_5f_sous-titre_3e_` : `front_sub`

### Les styles : 
- `Majuscule` : `style_uc`
- `PetiteMajuscule` : `style_sc`
- `italique` : `style_i`

**Comment by BineauJeanne** [comment]
Ok, nickel,  j'avais déjà commencé à changer les styles pour que ce soit plus facile à les retrouver mais c'est encore plus simple comme ça. Je changerai pour les maj et autres... J'ai aussi mis "typo_reg" pour "correctionTypo" et "typo_orig" pour les erreurs, "typo_restitution" pour "restitution" comme ça ils sont regroupés et c'est plus simple... Ça vous va ou vous voulez un autre nom ?

**Comment by NolwennCG** [comment]
Parfait ! Sauf pour `restitution`, ce n'est pas la peine : c'est une balise `damage` (je suis allée chercher dans le schéma BVH). Donne-moi ici la liste des balises que tu changeras, je ferai suivre le XSLT.

**Comment by BineauJeanne** [comment]
Nickel  pour "restitution", j'ai vu passer l'issue mais je n'avais pas encore intégré... Pour le moment, j'ai juste changé les style que je viens de te dire (typo_reg, typo_orig, style_uc, style_sc, style_i et les titres). J'ai aussi précisé pour les langues (lang_lat pour le latin) pour qu'il puisse y avoir un lang_ita (pour l'italien) pour le texte en bilingue italien (qui aura sans doute une locution latine). Je te tiens au courant pour le reste mais je pense que tu les as déjà traités dans cet issue. 

edit  : j'ai vu l'issue sur les langues, je change en "foreign_lat" ou autres langues

**Comment by BineauJeanne** [comment]
styles modifiés et ajoutés :

styles paragraphe :
- [x] front_main
- [x]  front_sub
- [x]  titre1
- [x]  titre2
- [x]  front_docImprint (pour les informations relatifs à l'impression, lieu et imprimeur)
- [x]  front_epigraph (pour l’épigraphe dans les préfaces)

styles de caractères : 
- [x]  style_uc
- [x]  style_sc
- [x]  style_i 
- [x]  foreign_lat
- [x]  damage
- [x]  typo_orig (erreur dans témoin)
- [x]  typo_reg (correction erreur)
- [x]  orn_fleuron
- [x]  orn_pied-de-mouche 
- [x]  pc (pour les guillemets et les parenthèses avec incises)


potentiellement (à vérifier dans la première transfo ODT > XML)
- [ ]  mevitalic
- [ ]  mevgras

**Comment by NolwennCG** [comment]
- Je ne comprends pas pour `orn_pied-de-mouche` : 
1. les pieds-de-mouche sont stylés ? Jusqu'ici je matchais "(C) "
2. l'attribut sera (voir le schéma des BVH) : "pied_de_mouche" donc le style devrait être nommé `orn_pied_de_mouche` 
- J'ai rajouté tout le reste.
