### ISSUE TITLE
Menu de sélection empiète sur l'affichage du texte

### ISSUE THREAD

**Issue by ghost** [OBVIL/faceties#57]
Le menu de sélection est fixé et empêche de lire une partie des textes (les titres)
Modifier la CSS en conséquence pour un affichage plus propre

**Comment by ghost** [comment]
À revoir au moment de l'intégration des PDF

**Comment by AnneLHuet** [comment]
L'ensemble du rendu en ligne a été revu (xml_html_orig.xsl & xml_html_reg.xsl)
