### ISSUE TITLE
Corrections des erreurs d'encodage dans le résultat de sortie

### ISSUE THREAD

**Issue by AnneLHuet** [OBVIL/faceties#62]
* [x] la balise `<front>` doit être contenue dans `<text>` et non dans `<body>`
* [x] la balise castList ne doit pas être systématique
* [x] la balise Standard doit être supprimée
* [x] remplacer l'attribut `lang` par `xml:lang`
* [x] remplacer `<c rend="lettrine"` par `<c type="lettrine">`
* [x] pour respecter le schéma des BVH, la page de titre devrait être encoder de la manière suivante : 
``` xml
        <front>
            <titlePage>
                <docTitle>
                    <titlePart type="main">[Titre principal]</titlePart>
                    <titlePart type="subtitle">[Sous-titre]</titlePart>
                </docTitle>
                <figure>
                    <graphic url="image.png"/>
                </figure>
                <docImprint>Imprimé à Blabla [front_docImprit]</docImprint>
                <epigraph>
                    <p>« ceci est un épigraphe »</p>
                </epigraph>
            </titlePage>
            <pb n="fa1v" xml:id="fa1v"/>
        </front>
```
* [x] ajouter le schéma automatiquement
```xml
<?xml-model href="../schema/BVH_Epistemon.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
```

* [x] ajouter l'attribut xmlns sur la racine: 
```xml
<TEI xmlns="http://www.tei-c.org/ns/1.0">
```

**Comment by ghost** [comment]
Ajout attribut xmlns et schema (pour l'instant dans branche corrections)

**Comment by ghost** [comment]
Corrections des problèmes listés
