### ISSUE TITLE
Les lettrines 5 ne sont pas affichées correctement

### ISSUE THREAD

**Issue by ghost** [OBVIL/faceties#67]
Les `lettrines 5` ne sont pas affichées dans le HTML, ni dans le XML.
Problème : dans la transformation `T1`, le `5` est supprimé du nom du style car il est souvent associé à des artefacts laissés par le format odt.
Solution : Tester si la balise en cours correspond au style `lettrine`

**Comment by AnneLHuet** [comment]
Le problème est résolu, je ferme l'issue !
